## 00. Pytorch Fundamentals

## Resource notebook:https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors
# PyTorch tensors are created using torch.Tensor()=https://pytorch.org/docs/stable/tensors.html

In [2]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
# Vector
vector=torch.tensor([7,7,7])
vector

tensor([7, 7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([3])

In [8]:
#MATRIX
MATRIX=torch.tensor([[7,8,6],[9,10,3]])
MATRIX

tensor([[ 7,  8,  6],
        [ 9, 10,  3]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8, 6])

In [11]:
MATRIX.shape

torch.Size([2, 3])

In [12]:
# TENSOR
TENSOR=torch.tensor([[[1,2,3],[3,4,6]],[[3,4,5],[6,7,8]]])
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([2, 2, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 6]])

In [15]:
TENSOR[0][1][2]

tensor(6)

### Random tensors
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data
Start with random numbers -> look at data ->update random numbers -> look at data ->update random numbers

In [16]:
# create a random tensor of size (3,,4)
rt=torch.rand(3,4)
rt

tensor([[0.4299, 0.5203, 0.9331, 0.5192],
        [0.6463, 0.4407, 0.7709, 0.4135],
        [0.5446, 0.5889, 0.9890, 0.2516]])

In [17]:
rt.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor
image_tensor=torch.rand(3,224,224)#color channels,height,width
image_tensor.shape

torch.Size([3, 224, 224])

In [19]:
image_tensor.ndim

3

## Zeros and ones

In [20]:
#Create a tensor of all zeros
z=torch.zeros(3,4)
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
z*rt

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
#All ones
o=torch.ones(3,4)
o

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
o.dtype

torch.float32

In [24]:
rt.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
one_to_ten=torch.range(0,10)

<ipython-input-25-af251a0039a9>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten=torch.range(0,10)


In [26]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#range is float32 and arange is int64

In [28]:
torch.arange(start=0,end=1000,step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
# Creating tensors like
ten_zeroes=torch.zeros_like(one_to_ten)#copying the shape of one_to_ten
ten_zeroes

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Tensor datatypes

In [30]:
a=torch.tensor([3,6,7])
a.dtype

torch.int64

In [31]:
a=torch.tensor([3.4,6.4,7],dtype=torch.int64)
a.dtype

torch.int64

In [32]:
#float 32 or 16 means precision

In [33]:
a=torch.tensor([3.4,6.4,7],
               dtype=None,#what datatype is the tensor
              device=None,#what device is your tensor on "cpu","cuda" etc
              requires_grad=False)#whether or not to track gradients with this tensors operations
a.dtype

torch.float32

In [34]:
float_32_tensor=torch.tensor([3.4,6.4,7])

In [35]:
float_16_tensor=float_32_tensor.type(torch.float16)#converting datatypes

In [36]:
float_32_tensor*float_16_tensor

tensor([11.5613, 40.9500, 49.0000])

In [37]:
int_32_tensor=torch.tensor([3,2,1])

In [38]:
float_32_tensor*int_32_tensor

tensor([10.2000, 12.8000,  7.0000])

### Getting info from tensors
1.Tensors not right datatype -to get datatype from tensor we use tensor.dtype
2.Tensors not right shape- to get shape we use tensor.shape
3.Tensors not on the right device-to get the device from a tensor we use tensor.device

In [39]:
a.dtype

torch.float32

In [40]:
a.shape

torch.Size([3])

In [41]:
a.device

device(type='cpu')

### Manipulating tensors(tensor operations)
Tensor operations include:
*Addition *Substraction *Multiplication *Division *Matrix Multiplication

In [42]:
#ADDITION
a=torch.tensor([1,2,3])
a+10

tensor([11, 12, 13])

In [43]:
a*10

tensor([10, 20, 30])

In [44]:
a-100

tensor([-99, -98, -97])

In [45]:
#Instead can also try pytorch inbuilt functions
torch.mul(a,7)# instead of * or can use * its fine

tensor([ 7, 14, 21])

In [46]:
torch.add(a,8)

tensor([ 9, 10, 11])

### Matrix multiplication

In [47]:
#Element wise multiplication
a*a

tensor([1, 4, 9])

In [48]:
print(a,"*",a)

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [49]:
print(f"a*a= {a*a}")

a*a= tensor([1, 4, 9])


In [50]:
#Matrix multiplication
torch.matmul(a,a)

tensor(14)

In [51]:
a @ a # @ is same as matmul

tensor(14)

In [52]:
#Matrix multiplication by hand
1*1+2*2+3*3

14

In [53]:
%%time
value=0
for i in range(len(a)):
    value+=a[i]*a[i]
print(value)

tensor(14)
CPU times: user 816 µs, sys: 0 ns, total: 816 µs
Wall time: 1.66 ms


In [54]:
%%time
torch.matmul(a,a)#0ns much faster

CPU times: user 35 µs, sys: 6 µs, total: 41 µs
Wall time: 44.8 µs


tensor(14)

### one of the most common errors in deep learning is shape errors
#### 1)1.Inner dimensions shud match (3,2) @ (3,2) wont work but (3,2) @ (2,3) works, here @ means matmul

In [56]:
torch.matmul(torch.rand(3,2),torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [57]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.4586, 0.5534, 0.6796],
        [0.3065, 0.3251, 0.1734],
        [0.9029, 0.9452, 0.4346]])

In [58]:
torch.rand(3,2)@torch.rand(2,3)

tensor([[0.9257, 0.7434, 1.1731],
        [0.8932, 0.8334, 1.1186],
        [0.2368, 0.2521, 0.2929]])

In [59]:
torch.rand(2,3)@torch.rand(3,2)

tensor([[1.2066, 1.1178],
        [0.3748, 0.4889]])

In [60]:
# SHAPES FOR MATRIX MULTIPLICATION
tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
tensor_B=torch.tensor([[1,2],[3,4],[5,6]])
torch.mm(tensor_A,tensor_B)#mm is same as matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [61]:
tensor_B=torch.tensor([[1,2,3],[4,5,6]])
torch.mm(tensor_A,tensor_B)

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

In [62]:
tensor_B=torch.tensor([[1,2],[3,4],[5,6]])

In [63]:
tensor_B.T#TRANSPOSE

tensor([[1, 3, 5],
        [2, 4, 6]])

## Finding the min,max,mean,sum,etc(tensor aggregation)

In [64]:
x=torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [65]:
torch.min(x)

tensor(0)

In [66]:
torch.max(x)

tensor(90)

In [67]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [68]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [69]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [70]:
x.type(torch.float32).mean()

tensor(45.)

In [71]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [72]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [73]:
x.argmax()

tensor(9)

## Reshaping , stacking,squeezing and unsqueezing tensors
### Reshaping -reshapes an input tensor to a defined shape
### View -Return a view of an input tensor of certain shape but keep the same memory of the original tensor
### Stacking-combine multiple tensors on top of each other (vstack) or side by side
### stack -https://pytorch.org/docs/stable/generated/torch.stack.html
### squeeze- removes all '1' dimension to a target tensor
### permute- return a view of the input with dimension permuted (swappe) in a certain way

In [74]:
x=torch.arange(1.,11.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [75]:
#add an extra dimension
x_reshaped=x.reshape([10,1])
x_reshaped

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [76]:
x_reshaped=x.reshape([5,2,1])
x_reshaped

tensor([[[ 1.],
         [ 2.]],

        [[ 3.],
         [ 4.]],

        [[ 5.],
         [ 6.]],

        [[ 7.],
         [ 8.]],

        [[ 9.],
         [10.]]])

In [77]:
#Change the view
z=x.view(1,10)
z,z.shape
#changing z changes x bcz they both share memory

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [78]:
#changing z
z[0][0]=5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [79]:
#stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=0)#v stack dim=0
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [80]:
x_stacked=torch.stack([x,x,x,x],dim=1)#h stack dim=1
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [81]:
#squeeze =removes all the single dimensions
x=torch.arange(1.,11.)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [82]:
x.squeeze().shape

torch.Size([10])

In [83]:
y=torch.rand([1,1,5])
y

tensor([[[0.8550, 0.4046, 0.6360, 0.1142, 0.1455]]])

In [84]:
y.squeeze().shape,y.squeeze()#see removed all faltu ke 1 dimensions

(torch.Size([5]), tensor([0.8550, 0.4046, 0.6360, 0.1142, 0.1455]))

In [85]:
#torch.unsqueeze()-adds a single dim to a tensor at a specific dimension
y.unsqueeze(dim=0),y.unsqueeze(dim=0).shape

(tensor([[[[0.8550, 0.4046, 0.6360, 0.1142, 0.1455]]]]),
 torch.Size([1, 1, 1, 5]))

In [86]:
#torch.permute-rearranges the data in tensor in a certain order
x=torch.rand(size=(224,224,3))#height,width,color channel for image
x.shape

torch.Size([224, 224, 3])

In [87]:
#permute x to rearrange the dimensions
x=torch.permute(x,(2,0,1))#colour columns(2) is 1st now (colour channel,height,width)
x.shape

torch.Size([3, 224, 224])

## Indexing  (selecting data from tensors)

In [88]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [89]:
#Let's index
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [90]:
x[0][0],x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [91]:
x[0][0][0]

tensor(1)

In [92]:
# you can also use ":" to select "all" of a target dimension
x[:,0]#all values from the

tensor([[1, 2, 3]])

In [93]:
# Get all values of the 0th and the 1st dimension but only index 1 of the 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [94]:
#Get all the values of the 0th dimension but only the 1 value of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [95]:
# get index 0 of 0th and 1st dim and all values of the 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [96]:
#Index on x to return 9
x[:,2,2]

tensor([9])

In [97]:
#Index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors and numpy

In [98]:
#Numpy array to tensor
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [99]:
array.dtype

dtype('float64')

In [100]:
torch.arange(1.0,8.0).dtype

torch.float32

In [101]:
#numpy default float datatype is float64 and tht of torch is float 32

In [102]:
#to change type
tensor=torch.from_numpy(array).type(torch.float32)

In [103]:
#tensor to numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## REPRODUCBILITY(trying to take random out of random)
How neural network learns:
start with random numbers=> tensor operations=>update random numbers to try and make them of the data => again=>again=>again..
### To reduce the randomness in neural networks and pytorch we used random seed
### Essentially what random seed does is "flavour " the randomness

In [104]:
torch.rand(3,3)#pseudo random ness or machine generated randomess

tensor([[0.7734, 0.7432, 0.8951],
        [0.0930, 0.7675, 0.3937],
        [0.5184, 0.2733, 0.2548]])

In [105]:
import torch
# create two randome tensors
r1=torch.rand(3,4)
r2=torch.rand(3,4)
print(r1)
print(r2)
print(r1==r2)

tensor([[0.3887, 0.6445, 0.8726, 0.4105],
        [0.1853, 0.1321, 0.2040, 0.4691],
        [0.9311, 0.3010, 0.2365, 0.1975]])
tensor([[0.4582, 0.2654, 0.6872, 0.5561],
        [0.9982, 0.3941, 0.5519, 0.7638],
        [0.8977, 0.7302, 0.2427, 0.0528]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [106]:
# Lets make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED=42#CAN SET TO WATVER(DIFF FLAVOUR TO RANDOMNESS)
torch.manual_seed(RANDOM_SEED)
rand1=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)#should cALL Bfr every tensor we want it to be similar
rand2=torch.rand(3,4)
rand1,rand2
rand1==rand2

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors and pytorch objects on the GPU'S (making the computations faster)
#### GPUs=faster computations on numbers, thanks to CUDA+NVIDIA hardware+pytorch

### 1.Getting a GPU
1.use google collab from 1 free GPU

In [107]:
torch.cuda.is_available()

True

In [108]:
import torch
print(torch.__version__)  # Check PyTorch version
print(torch.cuda.is_available())  # Check if GPU is detected
print(torch.cuda.device_count())  # Number of GPUs available
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU found")  # GPU name


2.6.0+cu124
True
1
Tesla T4


In [109]:
tensor=torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [112]:
tensor_gpu=tensor.to(device='cuda')
tensor_gpu.device

device(type='cuda', index=0)

In [114]:
tensor_back_to_cpu=tensor_gpu.cpu().numpy()
tensor_back_to_cpu.device#numpy doesnt work on gpu

'cpu'